/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Add card form request
 *
 * @param checkoutAccount Merchant ID
 * @param checkoutAlgorithm HMAC algorithm
 * @param checkoutRedirectSuccessUrl Merchant's url for user redirect on successful card addition
 * @param checkoutRedirectCancelUrl Merchant's url for user redirect on failed card addition
 * @param checkoutCallbackSuccessUrl Merchant's url called on successful card addition
 * @param checkoutCallbackCancelUrl Merchant's url called on failed card addition
 * @param language Alpha-2 language code for the card addition form
 */
@Serializable
data class AddCardFormRequest(

    /* Merchant ID */
    @SerialName(value = "checkout-account")
    val checkoutAccount: kotlin.Int,

    /* HMAC algorithm */
    @SerialName(value = "checkout-algorithm")
    val checkoutAlgorithm: AddCardFormRequest.CheckoutAlgorithm,

    /* Merchant's url for user redirect on successful card addition */
    @SerialName(value = "checkout-redirect-success-url")
    val checkoutRedirectSuccessUrl: kotlin.String,

    /* Merchant's url for user redirect on failed card addition */
    @SerialName(value = "checkout-redirect-cancel-url")
    val checkoutRedirectCancelUrl: kotlin.String,

    /* Merchant's url called on successful card addition */
    @SerialName(value = "checkout-callback-success-url")
    val checkoutCallbackSuccessUrl: kotlin.String? = null,

    /* Merchant's url called on failed card addition */
    @SerialName(value = "checkout-callback-cancel-url")
    val checkoutCallbackCancelUrl: kotlin.String? = null,

    /* Alpha-2 language code for the card addition form */
    @SerialName(value = "language")
    val language: AddCardFormRequest.Language? = null,

) {

    /**
     * HMAC algorithm
     *
     * Values: Sha256,Sha512
     */
    @Serializable
    enum class CheckoutAlgorithm(val value: kotlin.String) {
        @SerialName(value = "sha256")
        Sha256("sha256"),

        @SerialName(value = "sha512")
        Sha512("sha512"),
    }

    /**
     * Alpha-2 language code for the card addition form
     *
     * Values: FI,SV,EN
     */
    @Serializable
    enum class Language(val value: kotlin.String) {
        @SerialName(value = "FI")
        FI("FI"),

        @SerialName(value = "SV")
        SV("SV"),

        @SerialName(value = "EN")
        EN("EN"),
    }
}
