/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import fi.paytrail.sdk.apiclient.MerchantAccount
import fi.paytrail.sdk.apiclient.infrastructure.PaytrailHmacCalculator
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.reflect.full.memberProperties

/**
 * Add card form request
 *
 * @param checkoutAccount Merchant ID
 * @param checkoutAlgorithm HMAC algorithm
 * @param checkoutRedirectSuccessUrl Merchant's url for user redirect on successful card addition
 * @param checkoutRedirectCancelUrl Merchant's url for user redirect on failed card addition
 * @param checkoutCallbackSuccessUrl Merchant's url called on successful card addition
 * @param checkoutCallbackCancelUrl Merchant's url called on failed card addition
 * @param language Alpha-2 language code for the card addition form
 */
@Serializable
data class AddCardFormRequest(

    /* Merchant ID */
    @SerialName(value = "checkout-account")
    val checkoutAccount: Int,

    /* HMAC algorithm */
    @SerialName(value = "checkout-algorithm")
    val checkoutAlgorithm: String,

    @SerialName(value = "checkout-method")
    val checkoutMethod: String,

    @SerialName(value = "checkout-nonce")
    val checkoutNonce: String,

    @SerialName(value = "checkout-timestamp")
    val checkoutTimestamp: String,

    /* Merchant's url for user redirect on successful card addition */
    @SerialName(value = "checkout-redirect-success-url")
    val checkoutRedirectSuccessUrl: String,

    /* Merchant's url for user redirect on failed card addition */
    @SerialName(value = "checkout-redirect-cancel-url")
    val checkoutRedirectCancelUrl: String,

    /* Merchant's url called on successful card addition */
    @SerialName(value = "checkout-callback-success-url")
    val checkoutCallbackSuccessUrl: String? = null,

    /* Merchant's url called on failed card addition */
    @SerialName(value = "checkout-callback-cancel-url")
    val checkoutCallbackCancelUrl: String? = null,

    /* Alpha-2 language code for the card addition form */
    @SerialName(value = "language")
    val language: Language? = null,

) {
    @SerialName(value = "signature")
    val signature: String by lazy {
        PaytrailHmacCalculator
            .getCalculator(checkoutAlgorithm)
            .calculateHmac(
                params = asPostParams(includeSignature = false),
                key = MerchantAccount.account.secret,
            )
    }

    fun asPostParams(includeSignature: Boolean = true): Iterable<Pair<String, String>> =
        this::class.memberProperties
            .filter { property -> property.annotations.any { it is SerialName } }
            .filter { property ->
                includeSignature || property.annotations.none { annotation ->
                    annotation is SerialName && annotation.value == "signature"
                }
            }
            .filter { property -> property.getter.call(this) != null }
            .map { property ->
                val name = if (property.annotations.any { it is SerialName }) {
                    val nameAnnotation =
                        property.annotations.firstOrNull { it is SerialName } as? SerialName
                    nameAnnotation?.value ?: property.name
                } else {
                    property.name
                }

                val getter = property.getter
                val value = getter.call(this)
                property.returnType
                name to when (value) {
                    is String -> value
                    is Int -> value.toString()
                    is Language -> value.value
                    else -> throw RuntimeException("Unknown property type in ${this::class}: $property")
                }
            }
}
