/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param streetAddress Street address
 * @param postalCode Postal code
 * @param city City
 * @param country Alpha-2 country code
 * @param county County or top-level geographic subdivision
 */
@Serializable
data class Address(

    /* Street address */
    @SerialName(value = "streetAddress")
    val streetAddress: kotlin.String,

    /* Postal code */
    @SerialName(value = "postalCode")
    val postalCode: kotlin.String,

    /* City */
    @SerialName(value = "city")
    val city: kotlin.String,

    /* Alpha-2 country code */
    @SerialName(value = "country")
    val country: kotlin.String,

    /* County or top-level geographic subdivision */
    @SerialName(value = "county")
    val county: kotlin.String? = null,

)
