/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id ID of the provider
 * @param name Display name of the payment method
 * @param svg URL to payment method SVG icon (recommended to be used instead if PNG)
 * @param icon URL to payment method PNG icon
 * @param group
 */
@Serializable
data class BasePaymentMethodProvider(

    /* ID of the provider */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Display name of the payment method */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL to payment method SVG icon (recommended to be used instead if PNG) */
    @SerialName(value = "svg")
    val svg: kotlin.String,

    /* URL to payment method PNG icon */
    @SerialName(value = "icon")
    val icon: kotlin.String,

    @SerialName(value = "group")
    val group: BasePaymentMethodProvider.Group,

) {

    /**
     *
     *
     * Values: Mobile,Bank,Creditcard,Credit
     */
    @Serializable
    enum class Group(val value: kotlin.String) {
        @SerialName(value = "mobile")
        Mobile("mobile"),

        @SerialName(value = "bank")
        Bank("bank"),

        @SerialName(value = "creditcard")
        Creditcard("creditcard"),

        @SerialName(value = "credit")
        Credit("credit"),
    }
}
