/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param success URL to call when payment is succesfully paid. Can called multiple times; one must ensure idempotency of this endpoint.
 * @param cancel URL to call when payment is cancelled and not fulfilled. Can called multiple times; one must ensure idempotency of this endpoint.
 */
@Serializable
data class Callbacks(

    /* URL to call when payment is succesfully paid. Can called multiple times; one must ensure idempotency of this endpoint.  */
    @SerialName(value = "success")
    val success: kotlin.String,

    /* URL to call when payment is cancelled and not fulfilled. Can called multiple times; one must ensure idempotency of this endpoint.  */
    @SerialName(value = "cancel")
    val cancel: kotlin.String,

)
