/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param countryCode e.g. FI
 * @param type Card type, for example ‘Visa’
 * @param partialPan Last four digits of the card
 * @param expireYear Card expiration year
 * @param expireMonth Card expiration month
 * @param cvcRequired Whether the CVC is required for paying with this card. Can be one of yes, no or not_tested.
 * @param bin First 2 or 6 digits of the card number. (6 MC/VISA, 2 Amex/Diners)
 * @param funding credit, debit or unknown
 * @param category business, prepaid or unknown
 * @param cardFingerprint Identifies a specific card number. Cards with the same PAN but different expiry dates will have the same PAN fingerprint. Hex string of length 64.
 * @param panFingerprint Identifies a specific card, including the expiry date. Hex string of length 64.
 */
@Serializable
data class Card(

    /* e.g. FI */
    @SerialName(value = "country_code")
    val countryCode: kotlin.String,

    /* Card type, for example ‘Visa’ */
    @SerialName(value = "type")
    val type: kotlin.String? = null,

    /* Last four digits of the card */
    @SerialName(value = "partial_pan")
    val partialPan: kotlin.String? = null,

    /* Card expiration year */
    @SerialName(value = "expire_year")
    val expireYear: kotlin.String? = null,

    /* Card expiration month */
    @SerialName(value = "expire_month")
    val expireMonth: kotlin.String? = null,

    /* Whether the CVC is required for paying with this card. Can be one of yes, no or not_tested. */
    @SerialName(value = "cvc_required")
    val cvcRequired: kotlin.String? = null,

    /* First 2 or 6 digits of the card number. (6 MC/VISA, 2 Amex/Diners) */
    @SerialName(value = "bin")
    val bin: kotlin.String? = null,

    /* credit, debit or unknown */
    @SerialName(value = "funding")
    val funding: kotlin.String? = null,

    /* business, prepaid or unknown */
    @SerialName(value = "category")
    val category: kotlin.String? = null,

    /* Identifies a specific card number. Cards with the same PAN but different expiry dates will have the same PAN fingerprint. Hex string of length 64. */
    @SerialName(value = "card_fingerprint")
    val cardFingerprint: kotlin.String? = null,

    /* Identifies a specific card, including the expiry date. Hex string of length 64. */
    @SerialName(value = "pan_fingerprint")
    val panFingerprint: kotlin.String? = null,

)
