/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param email Customer email address
 * @param firstName Customer first name
 * @param lastName Customer last name
 * @param phone Customer phone number
 * @param vatId Company VAT ID in international format
 */
@Serializable
data class Customer(

    /* Customer email address */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Customer first name */
    @SerialName(value = "firstName")
    val firstName: kotlin.String? = null,

    /* Customer last name */
    @SerialName(value = "lastName")
    val lastName: kotlin.String? = null,

    /* Customer phone number */
    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    /* Company VAT ID in international format */
    @SerialName(value = "vatId")
    val vatId: kotlin.String? = null,

)
