/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param status
 * @param message Error description
 * @param meta Possible detailed error descriptions
 */
@Serializable
data class Error(

    @SerialName(value = "status")
    val status: Error.Status,

    /* Error description */
    @SerialName(value = "message")
    val message: kotlin.String,

    /* Possible detailed error descriptions */
    @SerialName(value = "meta")
    val meta: kotlin.collections.List<kotlin.String>? = null,

) {

    /**
     *
     *
     * Values: Error
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "error")
        Error("error"),
    }
}
