/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List grouped providers response body
 *
 * @param terms Localized text with a link to payment terms
 * @param groups Payment method group data for all of groups that are included in the query
 * @param providers A flat list of payment method providers
 */
@Serializable
data class GroupedPaymentProvidersResponse(

    /* Localized text with a link to payment terms */
    @SerialName(value = "terms")
    val terms: kotlin.String,

    /* Payment method group data for all of groups that are included in the query */
    @SerialName(value = "groups")
    val groups: kotlin.collections.List<PaymentMethodGroupDataWithProviders>,

    /* A flat list of payment method providers */
    @SerialName(value = "providers")
    val providers: kotlin.collections.List<PaymentMethodProviderInfo>,

)
