/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param redirectUrl URL of the payment flow, to which the user needs to be 302-redirected to
 * @param transactionId Assigned transaction ID for the payment
 */
@Serializable
data class PayAndAddCardResponse(

    /* URL of the payment flow, to which the user needs to be 302-redirected to */
    @SerialName(value = "redirectUrl")
    val redirectUrl: kotlin.String,

    /* Assigned transaction ID for the payment */
    @SerialName(value = "transactionId")
    val transactionId: kotlin.String,

)
