/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param url Form action url
 * @param parameters
 */
@Serializable
data class PaymentMethodProviderAllOf(

    /* Form action url */
    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<PaymentMethodProviderAllOfParameters>,

)
