/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response for a successful payment request. Mechant ecom site can then either redirect the user to the URL given in href, or render the payment provider forms onsite. For each payment method an HTML form needs to be rendered using the parameters returned for each payment method provider.
 *
 * @param transactionId Checkout assigned transaction ID for the payment.
 * @param href Unique URL to hosted payment gateway
 * @param terms Text containing a link to the terms of payment
 * @param groups Contains data about the payment method groups. Contains only the groups found in the response's providers.
 * @param providers
 */
@Serializable
data class PaymentRequestResponse(

    /* Checkout assigned transaction ID for the payment. */
    @Contextual @SerialName(value = "transactionId")
    val transactionId: java.util.UUID,

    /* Unique URL to hosted payment gateway */
    @SerialName(value = "href")
    val href: kotlin.String,

    /* Text containing a link to the terms of payment */
    @SerialName(value = "terms")
    val terms: kotlin.String? = null,

    /* Contains data about the payment method groups. Contains only the groups found in the response's providers. */
    @SerialName(value = "groups")
    val groups: kotlin.collections.List<PaymentMethodGroupData>? = null,

    @SerialName(value = "providers")
    val providers: kotlin.collections.List<PaymentMethodProvider>? = null,

)
