/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param name Name of the form input
 * @param `value` Value of the form input
 */
@Serializable
data class PaymentMethodProviderAllOfParameters(

    /* Name of the form input */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* Value of the form input */
    @SerialName(value = "value")
    val `value`: kotlin.String,

)
