/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ID, name and icon URLs for a payment method group
 *
 * @param id ID of the group
 * @param name Localized name of the group
 * @param icon URL to the group PNG icon
 * @param svg URL to the group SVG icon (recommended to be used instead if PNG)
 */
@Serializable
data class PaymentMethodGroupData(

    /* ID of the group */
    @SerialName(value = "id")
    val id: PaymentMethodGroupData.Id,

    /* Localized name of the group */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL to the group PNG icon */
    @SerialName(value = "icon")
    val icon: kotlin.String,

    /* URL to the group SVG icon (recommended to be used instead if PNG) */
    @SerialName(value = "svg")
    val svg: kotlin.String,

) {

    /**
     * ID of the group
     *
     * Values: Mobile,Bank,Creditcard,Credit
     */
    @Serializable
    enum class Id(val value: kotlin.String) {
        @SerialName(value = "mobile")
        Mobile("mobile"),

        @SerialName(value = "bank")
        Bank("bank"),

        @SerialName(value = "creditcard")
        Creditcard("creditcard"),

        @SerialName(value = "credit")
        Credit("credit"),
    }
}
