/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id ID of the group
 * @param name Localized name of the group
 * @param icon URL to the group PNG icon
 * @param svg URL to the group SVG icon (recommended to be used instead if PNG)
 * @param providers
 */
@Serializable
data class PaymentMethodGroupDataWithProviders(

    /* ID of the group */
    @SerialName(value = "id")
    val id: PaymentMethodGroupData.Id,

    /* Localized name of the group */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL to the group PNG icon */
    @SerialName(value = "icon")
    val icon: kotlin.String,

    /* URL to the group SVG icon (recommended to be used instead if PNG) */
    @SerialName(value = "svg")
    val svg: kotlin.String,

    @SerialName(value = "providers")
    val providers: kotlin.collections.List<PaymentMethodProviderInfo>,

)

/**
 * Payment provider information.
 * Similar to [PaymentMethodProvider] in [PaymentRequestResponse.providers], but the responses from
 * listing payment method providers do not contain the payment URL or form parameters.
 *
 * @param id ID of the provider
 * @param name Display name of the payment method
 * @param svg URL to payment method SVG icon (recommended to be used instead if PNG)
 * @param icon URL to payment method PNG icon
 * @param group
 */
@Serializable
data class PaymentMethodProviderInfo(

    /* ID of the provider */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Display name of the payment method */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL to payment method SVG icon (recommended to be used instead of PNG) */
    @SerialName(value = "svg")
    val svg: kotlin.String,

    /* URL to payment method PNG icon */
    @SerialName(value = "icon")
    val icon: kotlin.String,

    @SerialName(value = "group")
    val group: PaymentMethodProvider.Group,

) {

    /**
     *
     *
     * Values: Mobile,Bank,Creditcard,Credit
     */
    @Serializable
    enum class Group(val value: kotlin.String) {
        @SerialName(value = "mobile")
        Mobile("mobile"),

        @SerialName(value = "bank")
        Bank("bank"),

        @SerialName(value = "creditcard")
        Creditcard("creditcard"),

        @SerialName(value = "credit")
        Credit("credit"),
    }
}
