/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param callbackUrls
 * @param amount The amount to refund. Required for normal merchant accounts. SiS aggregate can refund the whole purchase by providing just the amount
 * @param refundStamp Merchant specific unique stamp for the refund
 * @param refundReference Merchant reference for the refund
 * @param items Item level refund information for SiS refunds.
 */
@Serializable
data class Refund(

    @SerialName(value = "callbackUrls")
    val callbackUrls: Callbacks,

    /* The amount to refund. Required for normal merchant accounts. SiS aggregate can refund the whole purchase by providing just the amount  */
    @SerialName(value = "amount")
    val amount: kotlin.Long? = null,

    /* Merchant specific unique stamp for the refund */
    @SerialName(value = "refundStamp")
    val refundStamp: kotlin.String? = null,

    /* Merchant reference for the refund */
    @SerialName(value = "refundReference")
    val refundReference: kotlin.String? = null,

    /* Item level refund information for SiS refunds. */
    @SerialName(value = "items")
    val items: kotlin.collections.List<RefundItem>? = null,

)
