/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response for a successful merchant initiated transaction payment request.
 *
 * @param transactionId Checkout assigned transaction ID for the payment.
 */
@Serializable
data class TokenMITPaymentResponse(

    /* Checkout assigned transaction ID for the payment. */
    @Contextual @SerialName(value = "transactionId")
    val transactionId: java.util.UUID,

)
