/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param token Token used to make authorization holds & charges on card
 * @param customer
 * @param card
 */
@Serializable
data class TokenizationRequestResponse(

    /* Token used to make authorization holds & charges on card */
    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "customer")
    val customer: TokenCustomerDetails? = null,

    @SerialName(value = "card")
    val card: Card? = null,

)
