/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Payment request payload
 *
 * @param stamp Merchant specific unique stamp
 * @param reference Merchant reference for the payment
 * @param amount Total amount of the payment (sum of items), VAT included
 * @param currency
 * @param language Alpha-2 language code for the payment process
 * @param items
 * @param customer
 * @param redirectUrls
 * @param token Payment card token received from request to /tokenization/{checkout-tokenization-id}
 * @param orderId Order ID. Used for eg. Collector payments order ID. If not given, merchant reference is used instead.
 * @param deliveryAddress
 * @param invoicingAddress
 * @param callbackUrls
 * @param callbackDelay Callback delay in seconds. If callback URLs and delay are provided, callbacks will be called after the delay.
 */
@Serializable
data class TokenPaymentRequest(

    /* Merchant specific unique stamp */
    @SerialName(value = "stamp")
    val stamp: kotlin.String,

    /* Merchant reference for the payment */
    @SerialName(value = "reference")
    val reference: kotlin.String,

    /* Total amount of the payment (sum of items), VAT included */
    @SerialName(value = "amount")
    val amount: kotlin.Long,

    @SerialName(value = "currency")
    val currency: TokenPaymentRequest.Currency,

    /* Alpha-2 language code for the payment process */
    @SerialName(value = "language")
    val language: TokenPaymentRequest.Language,

    @SerialName(value = "items")
    val items: kotlin.collections.List<Item>,

    @SerialName(value = "customer")
    val customer: Customer,

    @SerialName(value = "redirectUrls")
    val redirectUrls: Callbacks,

    /* Payment card token received from request to /tokenization/{checkout-tokenization-id} */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* Order ID. Used for eg. Collector payments order ID. If not given, merchant reference is used instead. */
    @SerialName(value = "orderId")
    val orderId: kotlin.String? = null,

    @SerialName(value = "deliveryAddress")
    val deliveryAddress: Address? = null,

    @SerialName(value = "invoicingAddress")
    val invoicingAddress: Address? = null,

    @SerialName(value = "callbackUrls")
    val callbackUrls: Callbacks? = null,

    /* Callback delay in seconds. If callback URLs and delay are provided, callbacks will be called after the delay. */
    @SerialName(value = "callbackDelay")
    val callbackDelay: kotlin.Int? = null,

) {

    /**
     *
     *
     * Values: EUR
     */
    @Serializable
    enum class Currency(val value: kotlin.String) {
        @SerialName(value = "EUR")
        EUR("EUR"),
    }

    /**
     * Alpha-2 language code for the payment process
     *
     * Values: FI,SV,EN
     */
    @Serializable
    enum class Language(val value: kotlin.String) {
        @SerialName(value = "FI")
        FI("FI"),

        @SerialName(value = "SV")
        SV("SV"),

        @SerialName(value = "EN")
        EN("EN"),
    }
}
