/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package fi.paytrail.sdk.apiclient.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response for a successful customer initiated transaction payment request.
 *
 * @param transactionId Checkout assigned transaction ID for the payment.
 * @param threeDSecureUrl URL for 3DS authentication step-up. If this is returned, merchants needs to redirect customer to this given URL for 3DS authentication.
 */
@Serializable
data class TokenCITPaymentResponse(

    /* Checkout assigned transaction ID for the payment. */
    @Contextual @SerialName(value = "transactionId")
    val transactionId: java.util.UUID,

    /* URL for 3DS authentication step-up. If this is returned, merchants needs to redirect customer to this given URL for 3DS authentication. */
    @SerialName(value = "threeDSecureUrl")
    val threeDSecureUrl: kotlin.String? = null,

)
