name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    env:
      REPORTS_PATH: /**/build/reports/ktlint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run ktlint
        run: ./gradlew ktlintCheck -Pktlint.outputToConsole=true --info
      - name: Upload ktlint Results to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ktlint-reports
          retention-days: 5
          path: ${{ env.REPORTS_PATH }}
      - name: Ktlint Report
        uses: yutailang0119/action-ktlint@v3
        if: always()
        with:
          report-path: ${{ env.REPORTS_PATH }}/**/*xml

  android_lint:
    timeout-minutes: 10
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version-file: /.java-version
      - name: Run Android Lint
        run: ./gradlew lint --info
      - name: Upload Lint Results to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: android-lint-reports
          retention-days: 5
          path: /**/build/reports/lint-results-*
      - name: Android Lint Reports
        uses: yutailang0119/action-android-lint@v3
        if: always()
        with:
          report-path: /**/build/reports/lint-results-debug.xml

  unit_tests:
    timeout-minutes: 10
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version-file: /.java-version
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest testReleaseUnitTest --info
      - name: Upload Test Results to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-reports
          retention-days: 5
          path: /**/build/reports/tests/**
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: /**/build/test-results/testDebugUnitTest/*.xml
          reporter: java-junit
